import { and, FixedArray, lshift, method, SmartContractLib } from 'scrypt-ts'
import {
    BN256,
    BN256Pairing,
    CurvePoint,
    FQ2,
    FQ12,
    G1Point,
    LineFuncRes,
    TwistPoint,
} from 'scrypt-ts-lib/dist/ec/bn256'
import { Proof } from 'scrypt-ts-lib/dist/zk/g16bn256'

export type PreparedLine = { a: FQ2; b: FQ2; c: FQ2 }
export type PairingResidueWitness = {
    residue: FQ12
    residueInverse: FQ12
    scale: bigint
}
export type PreparedVerifyingKey = {
    millerb1a1: FQ12
    gammaAbc: FixedArray<G1Point, 2>
    gammaLines: FixedArray<PreparedLine, 91>
    deltaLines: FixedArray<PreparedLine, 91>
    root27: FQ12
    root27Squared: FQ12
}

/**
 * Generated by scripts/generate-optimized-groth16.cjs.
 *
 * Evaluates the three runtime Groth16 pairings in one unrolled Miller loop,
 * sharing the FQ12 squaring at every digit. The pairing equation and final
 * exponentiation are identical to the stock scrypt-ts-lib verifier.
 */
export class OptimizedG16BN256 extends SmartContractLib {
    @method()
    static mulG1PointBounded(a: G1Point, scalar: bigint): G1Point {
        const point = BN256.createCurvePoint(a)
        let t: CurvePoint = { x: 0n, y: 0n, z: 0n, t: 0n }
        let sum: CurvePoint = { x: 0n, y: 1n, z: 0n, t: 0n }
        let firstOne = false
        for (let k = 0; k < 128; k++) {
            sum = BN256.modCurvePoint(sum)
            for (let j = 0; j < 2; j++) {
                if (firstOne) {
                    t = BN256.doubleCurvePoint(sum)
                }
                const shifted = lshift(1n, BigInt(255 - (2 * k + j)))
                if (and(scalar, shifted) != 0n) {
                    firstOne = true
                    sum = BN256.addCurvePoints(t, point)
                } else {
                    sum = t
                }
            }
        }
        return BN256.getG1Point(sum)
    }

    @method()
    static mulPreparedLine(acc: FQ12, line: PreparedLine, p: CurvePoint): FQ12 {
        const b = BN256.mulScalarFQ2(line.b, p.x)
        const c = BN256.mulScalarFQ2(line.c, p.y)
        return BN256.modFQ12(BN256Pairing.mulLine(acc, line.a, b, c))
    }

    @method()
    static finishPair(
        acc: FQ12,
        r: TwistPoint,
        q: TwistPoint,
        p: CurvePoint
    ): FQ12 {
        let q1x = BN256.conjugateFQ2(q.x)
        q1x = BN256.mulFQ2(q1x, BN256.xiToPMinus1Over3)
        let q1y = BN256.conjugateFQ2(q.y)
        q1y = BN256.mulFQ2(q1y, BN256.xiToPMinus1Over2)
        const q1: TwistPoint = {
            x: q1x,
            y: q1y,
            z: { x: 0n, y: 1n },
            t: { x: 0n, y: 1n },
        }
        const minusQ2: TwistPoint = {
            x: BN256.mulScalarFQ2(q.x, BN256.xiToPSquaredMinus1Over3),
            y: q.y,
            z: { x: 0n, y: 1n },
            t: { x: 0n, y: 1n },
        }
        let line = BN256Pairing.lineFuncAdd(r, q1, p, BN256.squareFQ2(q1.y))
        acc = BN256Pairing.mulLine(acc, line.a, line.b, line.c)
        acc = BN256.modFQ12(acc)
        line = BN256Pairing.lineFuncAdd(
            BN256.modTwistPoint(line.rOut),
            minusQ2,
            p,
            BN256.squareFQ2(minusQ2.y)
        )
        return BN256.modFQ12(BN256Pairing.mulLine(acc, line.a, line.b, line.c))
    }

    @method()
    static millerPrepared3(
        q0Input: TwistPoint,
        p0Input: CurvePoint,
        p1Input: CurvePoint,
        p2Input: CurvePoint,
        gammaLines: FixedArray<PreparedLine, 91>,
        deltaLines: FixedArray<PreparedLine, 91>,
        initialAccumulator: FQ12,
        inverseAccumulator: FQ12
    ): FQ12 {
        const q0 = BN256.makeAffineTwistPoint(q0Input)
        const p0 = BN256.makeAffineCurvePoint(p0Input)
        const p1 = BN256.makeAffineCurvePoint(p1Input)
        const p2 = BN256.makeAffineCurvePoint(p2Input)
        const q0Minus = BN256.negTwistPoint(q0)
        const addR20 = BN256.squareFQ2(q0.y)
        let acc = initialAccumulator
        let r0 = q0
        let line0: LineFuncRes = BN256Pairing.lineFuncDouble(r0, p0)

        // Miller digit 0: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[0], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[0], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[1], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[1], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 1: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[2], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[2], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 2: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[3], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[3], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[4], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[4], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 3: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[5], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[5], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 4: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[6], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[6], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 5: -1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, inverseAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[7], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[7], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0Minus, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[8], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[8], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 6: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[9], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[9], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 7: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[10], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[10], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[11], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[11], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 8: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[12], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[12], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[13], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[13], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 9: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[14], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[14], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 10: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[15], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[15], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 11: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[16], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[16], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 12: -1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, inverseAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[17], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[17], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0Minus, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[18], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[18], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 13: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[19], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[19], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 14: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[20], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[20], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 15: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[21], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[21], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[22], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[22], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 16: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[23], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[23], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[24], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[24], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 17: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[25], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[25], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 18: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[26], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[26], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 19: -1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, inverseAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[27], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[27], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0Minus, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[28], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[28], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 20: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[29], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[29], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 21: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[30], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[30], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 22: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[31], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[31], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 23: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[32], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[32], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 24: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[33], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[33], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 25: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[34], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[34], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[35], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[35], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 26: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[36], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[36], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 27: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[37], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[37], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 28: -1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, inverseAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[38], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[38], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0Minus, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[39], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[39], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 29: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[40], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[40], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 30: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[41], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[41], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 31: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[42], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[42], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[43], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[43], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 32: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[44], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[44], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[45], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[45], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 33: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[46], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[46], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[47], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[47], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 34: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[48], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[48], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 35: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[49], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[49], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 36: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[50], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[50], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 37: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[51], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[51], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 38: -1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, inverseAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[52], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[52], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0Minus, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[53], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[53], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 39: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[54], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[54], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 40: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[55], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[55], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[56], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[56], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 41: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[57], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[57], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 42: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[58], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[58], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 43: -1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, inverseAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[59], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[59], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0Minus, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[60], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[60], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 44: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[61], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[61], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 45: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[62], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[62], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[63], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[63], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 46: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[64], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[64], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[65], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[65], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 47: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[66], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[66], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 48: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[67], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[67], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 49: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[68], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[68], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[69], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[69], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 50: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[70], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[70], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 51: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[71], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[71], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 52: -1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, inverseAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[72], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[72], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0Minus, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[73], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[73], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 53: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[74], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[74], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[75], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[75], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 54: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[76], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[76], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 55: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[77], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[77], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 56: -1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, inverseAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[78], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[78], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0Minus, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[79], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[79], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 57: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[80], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[80], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 58: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[81], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[81], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[82], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[82], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 59: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[83], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[83], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 60: 1
        acc = BN256.squareFQ12(acc)
        acc = BN256.mulFQ12(acc, initialAccumulator)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[84], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[84], p2)
        r0 = BN256.modTwistPoint(line0.rOut)
        line0 = BN256Pairing.lineFuncAdd(r0, q0, p0, addR20)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[85], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[85], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 61: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[86], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[86], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 62: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[87], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[87], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        // Miller digit 63: 0
        acc = BN256.squareFQ12(acc)
        line0 = BN256Pairing.lineFuncDouble(r0, p0)
        acc = BN256Pairing.mulLine(acc, line0.a, line0.b, line0.c)
        acc = BN256.modFQ12(acc)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[88], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[88], p2)
        r0 = BN256.modTwistPoint(line0.rOut)

        acc = OptimizedG16BN256.finishPair(acc, r0, q0, p0)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[89], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[89], p2)
        acc = OptimizedG16BN256.mulPreparedLine(acc, gammaLines[90], p1)
        acc = OptimizedG16BN256.mulPreparedLine(acc, deltaLines[90], p2)
        return BN256.modFQ12(acc)
    }

    @method()
    static verify(
        signal: bigint,
        proof: Proof,
        residueWitness: PairingResidueWitness,
        vk: PreparedVerifyingKey
    ): boolean {
        const scaled = OptimizedG16BN256.mulG1PointBounded(
            vk.gammaAbc[1],
            signal
        )
        const vkX = BN256.addG1Points(vk.gammaAbc[0], scaled)
        const negA: G1Point = { x: proof.a.x, y: -proof.a.y }
        const millerProduct = OptimizedG16BN256.millerPrepared3(
            BN256.createTwistPoint(proof.b),
            BN256.createCurvePoint(negA),
            BN256.createCurvePoint(vkX),
            BN256.createCurvePoint(proof.c),
            vk.gammaLines,
            vk.deltaLines,
            residueWitness.residueInverse,
            residueWitness.residue
        )
        let left = BN256.modFQ12(
            BN256.mulFQ12(vk.millerb1a1, millerProduct)
        )
        let validScale = true
        if (residueWitness.scale == 1n) {
            left = BN256.modFQ12(BN256.mulFQ12(left, vk.root27))
        } else if (residueWitness.scale == 2n) {
            left = BN256.modFQ12(BN256.mulFQ12(left, vk.root27Squared))
        } else if (residueWitness.scale != 0n) {
            validScale = false
        }

        const inverseCheck = BN256.modFQ12(
            BN256.mulFQ12(
                residueWitness.residue,
                residueWitness.residueInverse
            )
        )
        const inverseP = BN256.frobeniusFQ12(residueWitness.residueInverse)
        const inverseP2 = BN256.frobeniusP2FQ12(residueWitness.residueInverse)
        const inverseP3 = BN256.frobeniusFQ12(inverseP2)
        left = BN256.modFQ12(BN256.mulFQ12(left, inverseP3))
        left = BN256.modFQ12(BN256.mulFQ12(left, inverseP))
        return (
            validScale &&
            BN256.compareFQ12(inverseCheck, BN256.FQ12One) &&
            BN256.compareFQ12(left, inverseP2)
        )
    }
}
